/**
 * Role statistics from 2,146 parsed Avalon games (2020-2023).
 * Source: content/_data/roles/ JSON files generated by parse_roles.py (M0.3).
 * Canonical 7 roles only.
 */

export interface SeatWinRates {
  [seat: string]: number;
}

export interface ResultBreakdown {
  /** Evil wins 3 quests */
  '\u4e09\u7d05': number;
  /** Good wins 3 quests but Merlin assassinated */
  '\u4e09\u85cd\u6b7b': number;
  /** Good wins 3 quests and Merlin survives */
  '\u4e09\u85cd\u6d3b': number;
}

export interface RoleStats {
  total_games: number;
  wins: number;
  losses: number;
  win_rate: number;
  aggregate_win_rate: number;
  result_breakdown: ResultBreakdown;
  seat_distribution: Record<string, number>;
  seat_win_rates: SeatWinRates;
}

export interface RoleData {
  id: string;
  slug: string;
  name_zh: string;
  name_en: string;
  faction: 'good' | 'evil';
  abbrev: string;
  ability: string;
  stats: RoleStats;
}

export const ROLE_STATS: Record<string, RoleData> = {
  merlin: {
    id: 'merlin',
    slug: 'merlin',
    name_zh: '\u6885\u6797',
    name_en: 'Merlin',
    faction: 'good',
    abbrev: '\u6885',
    ability: '\u77e5\u9053\u6240\u6709\u7d05\u65b9\u8eab\u4efd\uff08\u9664\u83ab\u5fb7\u96f7\u5fb7\uff09\uff0c\u4f46\u9700\u96b1\u85cf\u81ea\u5df1\u4e0d\u88ab\u523a\u6bba',
    stats: {
      total_games: 859,
      wins: 535,
      losses: 324,
      win_rate: 0.6228,
      aggregate_win_rate: 0.284,
      result_breakdown: { '\u4e09\u7d05': 324, '\u4e09\u85cd\u6b7b': 247, '\u4e09\u85cd\u6d3b': 288 },
      seat_distribution: { '0': 198, '1': 208, '4': 227, '5': 226 },
      seat_win_rates: { '0': 0.6364, '1': 0.524, '4': 0.5727, '5': 0.7522 },
    },
  },
  percival: {
    id: 'percival',
    slug: 'percival',
    name_zh: '\u6d3e\u897f\u7dad\u723e',
    name_en: 'Percival',
    faction: 'good',
    abbrev: '\u6d3e',
    ability: '\u77e5\u9053\u6885\u6797\u548c\u83ab\u7518\u5a1c\u7684\u8eab\u4efd\uff08\u4f46\u7121\u6cd5\u5206\u8fa8\u8ab0\u662f\u8ab0\uff09',
    stats: {
      total_games: 823,
      wins: 489,
      losses: 334,
      win_rate: 0.5942,
      aggregate_win_rate: 0.7346,
      result_breakdown: { '\u4e09\u7d05': 334, '\u4e09\u85cd\u6b7b': 223, '\u4e09\u85cd\u6d3b': 266 },
      seat_distribution: { '0': 224, '1': 203, '4': 209, '5': 187 },
      seat_win_rates: { '0': 0.6384, '1': 0.5665, '4': 0.5072, '5': 0.6684 },
    },
  },
  loyal_servant: {
    id: 'loyal_servant',
    slug: 'loyal-servant',
    name_zh: '\u5fe0\u81e3',
    name_en: 'Loyal Servant',
    faction: 'good',
    abbrev: '\u5fe0',
    ability: '\u7121\u7279\u6b8a\u80fd\u529b\uff0c\u4f9d\u9760\u63a8\u7406\u548c\u6295\u7968\u5e6b\u52a9\u85cd\u65b9',
    stats: {
      total_games: 3475,
      wins: 1935,
      losses: 1540,
      win_rate: 0.5568,
      aggregate_win_rate: 0.275,
      result_breakdown: { '\u4e09\u7d05': 1540, '\u4e09\u85cd\u6b7b': 828, '\u4e09\u85cd\u6d3b': 1107 },
      seat_distribution: { '0': 890, '1': 886, '4': 862, '5': 837 },
      seat_win_rates: { '0': 0.5663, '1': 0.5395, '4': 0.5441, '5': 0.5783 },
    },
  },
  mordred: {
    id: 'mordred',
    slug: 'mordred',
    name_zh: '\u83ab\u5fb7\u96f7\u5fb7',
    name_en: 'Mordred',
    faction: 'evil',
    abbrev: '\u5fb7',
    ability: '\u6885\u6797\u7121\u6cd5\u770b\u5230\u83ab\u5fb7\u96f7\u5fb7\uff0c\u662f\u7d05\u65b9\u6700\u5f37\u7684\u96b1\u85cf\u89d2\u8272',
    stats: {
      total_games: 899,
      wins: 435,
      losses: 464,
      win_rate: 0.4839,
      aggregate_win_rate: 0.725,
      result_breakdown: { '\u4e09\u7d05': 435, '\u4e09\u85cd\u6b7b': 217, '\u4e09\u85cd\u6d3b': 247 },
      seat_distribution: { '0': 213, '1': 219, '4': 229, '5': 238 },
      seat_win_rates: { '0': 0.4883, '1': 0.4703, '4': 0.4323, '5': 0.542 },
    },
  },
  morgana: {
    id: 'morgana',
    slug: 'morgana',
    name_zh: '\u83ab\u7518\u5a1c',
    name_en: 'Morgana',
    faction: 'evil',
    abbrev: '\u5a1c',
    ability: '\u5728\u6d3e\u897f\u7dad\u723e\u773c\u4e2d\u8207\u6885\u6797\u76f8\u540c\uff0c\u7528\u4f86\u8ff7\u60d1\u85cd\u65b9',
    stats: {
      total_games: 840,
      wins: 413,
      losses: 427,
      win_rate: 0.4917,
      aggregate_win_rate: 0.7152,
      result_breakdown: { '\u4e09\u7d05': 413, '\u4e09\u85cd\u6b7b': 194, '\u4e09\u85cd\u6d3b': 233 },
      seat_distribution: { '0': 227, '1': 196, '4': 209, '5': 208 },
      seat_win_rates: { '0': 0.4978, '1': 0.449, '4': 0.4833, '5': 0.5337 },
    },
  },
  assassin: {
    id: 'assassin',
    slug: 'assassin',
    name_zh: '\u523a\u5ba2',
    name_en: 'Assassin',
    faction: 'evil',
    abbrev: '\u523a',
    ability: '\u85cd\u65b9\u4e09\u52dd\u5f8c\u53ef\u523a\u6bba\u6885\u6797\uff0c\u523a\u4e2d\u5247\u7d05\u65b9\u9006\u8f49\u52dd',
    stats: {
      total_games: 828,
      wins: 432,
      losses: 396,
      win_rate: 0.5217,
      aggregate_win_rate: 0.6254,
      result_breakdown: { '\u4e09\u7d05': 432, '\u4e09\u85cd\u6b7b': 154, '\u4e09\u85cd\u6d3b': 242 },
      seat_distribution: { '0': 193, '1': 223, '4': 190, '5': 222 },
      seat_win_rates: { '0': 0.5648, '1': 0.4529, '4': 0.4632, '5': 0.6036 },
    },
  },
  oberon: {
    id: 'oberon',
    slug: 'oberon',
    name_zh: '\u5967\u4f2f\u502b',
    name_en: 'Oberon',
    faction: 'evil',
    abbrev: '\u5967',
    ability: '\u4e0d\u77e5\u9053\u5176\u4ed6\u7d05\u65b9\u662f\u8ab0\uff0c\u5176\u4ed6\u7d05\u65b9\u4e5f\u770b\u4e0d\u5230\u5967\u4f2f\u502b',
    stats: {
      total_games: 860,
      wins: 406,
      losses: 454,
      win_rate: 0.4721,
      aggregate_win_rate: 0.7329,
      result_breakdown: { '\u4e09\u7d05': 406, '\u4e09\u85cd\u6b7b': 201, '\u4e09\u85cd\u6d3b': 253 },
      seat_distribution: { '0': 201, '1': 211, '4': 220, '5': 228 },
      seat_win_rates: { '0': 0.5274, '1': 0.3981, '4': 0.4091, '5': 0.5526 },
    },
  },
};

/** Map wiki article IDs to role stat keys */
export const ARTICLE_TO_ROLE: Record<string, string> = {
  'roles-merlin': 'merlin',
  'roles-percival': 'percival',
  'roles-loyal': 'loyal_servant',
  'roles-assassin': 'assassin',
  'roles-morgana': 'morgana',
  'roles-mordred': 'mordred',
  'roles-oberon': 'oberon',
};

/** Get all roles sorted: good first, then evil */
export function getAllRoles(): RoleData[] {
  const good = ['merlin', 'percival', 'loyal_servant'];
  const evil = ['mordred', 'morgana', 'assassin', 'oberon'];
  return [...good, ...evil].map((k) => ROLE_STATS[k]);
}

/** Format win rate as percentage string */
export function formatWinRate(rate: number): string {
  return `${(rate * 100).toFixed(1)}%`;
}

/** Total games across all roles (unique games, not role-appearances) */
export const TOTAL_UNIQUE_GAMES = 2146;
